FROM python:3.9
MAINTAINER Queens University Belfast d.capparelli@qub.ac.uk

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y \
    python3-pip \
    make

ADD app /OnAirScreen

WORKDIR /OnAirScreen

RUN pip install -r requirements.txt

RUN make

RUN make install

ENTRYPOINT /OnAirScreen/start.py
